from typing import Union, List, Dict, Any
from typing_extensions import TypedDict


class BaseConfig(TypedDict):
    RETRIEVER: str
    EMBEDDING: str
    SIMILARITY_THRESHOLD: float
    FAST_LLM: str
    SMART_LLM: str
    STRATEGIC_LLM: str
    FAST_TOKEN_LIMIT: int
    SMART_TOKEN_LIMIT: int
    STRATEGIC_TOKEN_LIMIT: int
    BROWSE_CHUNK_MAX_LENGTH: int
    SUMMARY_TOKEN_LIMIT: int
    TEMPERATURE: float
    USER_AGENT: str
    MAX_SEARCH_RESULTS_PER_QUERY: int
    MEMORY_BACKEND: str
    TOTAL_WORDS: int
    REPORT_FORMAT: str
    REPORT_STYLE: str
    SOURCE_POLICY: str
    CURATE_SOURCES: bool
    MAX_ITERATIONS: int
    LANGUAGE: str
    AGENT_ROLE: Union[str, None]
    SCRAPER: str
    MAX_SCRAPER_WORKERS: int
    SCRAPER_RATE_LIMIT_DELAY: float
    MAX_SUBTOPICS: int
    REPORT_SOURCE: Union[str, None]
    DOC_PATH: str
    PROMPT_FAMILY: str
    LLM_KWARGS: dict
    EMBEDDING_KWARGS: dict
    VERBOSE: bool
    DEEP_RESEARCH_CONCURRENCY: int
    DEEP_RESEARCH_DEPTH: int
    DEEP_RESEARCH_BREADTH: int
    DEEP_RESEARCH_MODE: str
    ADAPTIVE_MIN_DEPTH: int
    ADAPTIVE_MAX_DEPTH: int
    ADAPTIVE_RUN_TIMEOUT_SECONDS: int
    ADAPTIVE_QUALITY_THRESHOLD: float
    ADAPTIVE_SEARCH_TIMEOUT_SECONDS: int
    ADAPTIVE_QUERY_MATRIX_TIMEOUT_SECONDS: int
    ADAPTIVE_CLAIM_EXTRACTION_TIMEOUT_SECONDS: int
    ADAPTIVE_MAX_CONSECUTIVE_EMPTY_ROUNDS: int
    ADAPTIVE_MAX_CONFLICTS_PER_NODE: int
    ADAPTIVE_MAX_DIMENSIONS: int
    ADAPTIVE_SOURCE_QUALITY_FILTER_ENABLED: bool
    ADAPTIVE_MAX_SOURCES_PER_QUERY: int
    ADAPTIVE_MAX_SOURCES_PER_DOMAIN: int
    ADAPTIVE_MIN_SOURCE_QUALITY_SCORE: float
    ADAPTIVE_REQUIRE_HIGH_QUALITY_SOURCE_QUOTA: bool
    ADAPTIVE_HIGH_QUALITY_SOURCE_QUOTA: float
    ADAPTIVE_HIGH_QUALITY_DOMAINS: List[str]
    ADAPTIVE_LOW_QUALITY_DOMAINS: List[str]
    ADAPTIVE_CACHE_ENABLED: bool
    ADAPTIVE_MAX_ROUNDS_PER_NODE: int
    ADAPTIVE_MAX_QUERIES_PER_ROUND: int
    ADAPTIVE_MAX_QUERY_FAILURES_PER_NODE: int
    ADAPTIVE_FAILURE_RATE_REDUCE_THRESHOLD: float
    ADAPTIVE_QUERY_MATRIX_LLM_DISABLE_AFTER_FAILURES: int
    ADAPTIVE_CLAIM_LLM_DISABLE_AFTER_FAILURES: int
    ADAPTIVE_FAILED_DOMAIN_THRESHOLD: int
    ADAPTIVE_MIN_COMPLETED_NODES_FOR_EARLY_STOP: int
    ADAPTIVE_COVERAGE_ENHANCER_ENABLED: bool
    ADAPTIVE_COVERAGE_MIN_RATIO: float
    ADAPTIVE_COVERAGE_REVISE_MAX_ROUNDS: int
    ADAPTIVE_COVERAGE_PROFILE: str
    ENTROPY_MIN_GAIN: float
    SALIENCY_THRESHOLD: float
    RABBIT_HOLE_MAX_BRANCHES: int
    RABBIT_HOLE_MAX_QUERIES_PER_BRANCH: int
    TAVILY_SEARCH_DEPTH_DEFAULT: str
    TAVILY_ADVANCED_ENABLED: bool
    REPORT_COMPLETION_GUARD_ENABLED: bool
    REPORT_COMPLETION_MAX_ATTEMPTS: int
    REPORT_COMPLETION_REQUIRE_MARKER: bool
    REPORT_SECTIONAL_FALLBACK_ENABLED: bool
    REPORT_SECTIONAL_MAX_SECTIONS: int
    REPORT_SECTIONAL_CONTEXT_CHARS: int
    REPORT_SECTIONAL_PREFLIGHT_ENABLED: bool
    REPORT_SECTIONAL_PREFLIGHT_MIN_CONTEXT_CHARS: int
    REPORT_SECTIONAL_TIMEOUT_SECONDS: int
    REPORT_SECTIONAL_FALLBACK_REDUCED_MAX_SECTIONS: int
    REPORT_SECTIONAL_FALLBACK_REDUCED_CONTEXT_CHARS: int
    MCP_SERVERS: List[Dict[str, Any]]
    MCP_AUTO_TOOL_SELECTION: bool
    MCP_USE_LLM_ARGS: bool
    MCP_ALLOWED_ROOT_PATHS: List[str]
    MCP_STRATEGY: str
    REASONING_EFFORT: str
    # Image generation settings
    IMAGE_GENERATION_MODEL: Union[str, None]
    IMAGE_GENERATION_MAX_IMAGES: int
    IMAGE_GENERATION_ENABLED: bool
    IMAGE_GENERATION_STYLE: str  # Image style: "dark", "light", or "auto"
